FROM php:7.0-apache

COPY ./apache2.conf /etc/apache2/conf-enabled/docker-php.conf
COPY ./test1.php /var/www/html/test1.php
COPY ./test2.php /var/www/html/test2.php
COPY ./test3.php /var/www/html/test3.php
